---
title: "Some study on rasters"
output: 
  html_document: 
    fig_height: 6
    fig_width: 9
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = TRUE)
```


```{r, echo = FALSE, eval = FALSE}
# https://rpubs.com/etiennebr/visualraster

```


```{r}
library(raster)
library(gdalUtils)
library(rasterVis)
library(tidyverse)
library(patchwork)
```


```{r, eval = FALSE}
crs_data <- rgdal::make_EPSG()
```


```{r}
r2df <- function(r, label = NULL) {
  d <-
    r %>% 
    as.data.frame(xy = TRUE)
  colnames(d)[3] <- "z"
  d$object <- label
  attributes(d)$e <- r %>% extent() %>% as.vector()
  return(d)
}
my_layers <- function(d, colour = "grey") {
  list(data = d, 
       geom_rect(xmin = attributes(d)$e[1],
                 xmax = attributes(d)$e[2], 
                 ymin = attributes(d)$e[3],
                 ymax = attributes(d)$e[4],
                 alpha = 0,
                 col = colour,
                 lwd = 4),
       geom_tile(data = d, aes(x, y, fill = z), colour = colour),
       geom_text(data = d, aes(x, y, label = z), colour = "white"),
       theme(legend.position = "none",
             panel.grid.minor = element_blank()),
       coord_equal())
}
tidy_raster <- function(r) {
  e <- extent(r)
  rs <- res(r)
  d <- dim(r)
  tibble(xmin = e[1],
         xmax = e[2],
         ymin = e[3],
         ymax = e[4],
         rx = rs[1],
         ry = rs[2],
         nrow = d[1],
         ncol = d[2],
         ncell = d[3])
}
my_plot <- function(r, object = "r1", colour, at) {
  
  if(missing(at)) {
    at <- tidy_raster(r) %>% mutate(object = object)
  }
  p <- 
    r %>% 
    r2df(object) %>% 
    ggplot() +
    geom_tile(aes(x, y, fill = z), colour = "white") +
    geom_text(aes(x, y, label = z), colour = "white") +
    facet_wrap(~ object, nrow = 1) +
    coord_equal() +
    theme(legend.position = "none",
          panel.grid.minor = element_blank()) +
    scale_x_continuous(name = NULL, breaks = 0:6, limits = c(0, 6)) +
    scale_y_continuous(name = NULL, breaks = 0:6, limits = c(0, 6))
  
  if(!missing(colour)) {
    p <-
      p +
      geom_rect(data = at, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = colour)
  }
  
  return(p)
}
```

# Tidy rasters

## Base

```{r, include = FALSE}
r1 <- 
  raster(res = c(1, 1),
         xmn = 1, xmx = 4, ymn = 1, ymx = 4,
         vals = 1)
writeRaster(r1, "r1.tif", overwrite = TRUE)
r2 <- 
  raster(res = c(1, 1),
         xmn = 2, xmx = 5, ymn = 2, ymx = 5,
         vals = 2)
writeRaster(r2, "r2.tif", overwrite = TRUE)

r3 <- merge(r1, r2)
r4 <- merge(r2, r1)
r5 <- mosaic(r1, r2, fun = "mean")
r6 <- mosaic(r2, r1, fun = "mean")
dummy <- mosaic_rasters(c("r1.tif", "r2.tif"), dst_dataset = "r7.tif", fun = "mean")
r7 <- raster("r7.tif")
dummy <- mosaic_rasters(c("r2.tif", "r1.tif"), dst_dataset = "r8.tif")
r8 <- raster("r8.tif")
```

```{r}
p1 <- my_plot(r1, "r1", colour = "red")
p2 <- my_plot(r2, "r2", colour = "red")
p3 <- 
  my_plot(r3, "r1, r2") +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 5.5, label = 'merge(r1, r2)', hjust = 0)
p4 <- 
  my_plot(r4, "r2, r1") +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 5.5, label = 'merge(r2, r1)', hjust = 0)
p5 <- 
  my_plot(r5, "r1, r2") +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 5.5, label = 'mosaic(r1, r2, fun = "mean")', hjust = 0)
p6 <- 
  my_plot(r6, "r2, r1") +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 5.5, label = 'mosaic(r2, r1, fun = "mean")', hjust = 0)
p7 <- 
  my_plot(r7, "r1, r2") +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 5.5, label = 'mosaic_rasters(r1, r2)', hjust = 0)
p8 <- 
  my_plot(r8, "r2, r1") +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 5.5, label = 'mosaic_rasters(r2, r1)', hjust = 0)
p1 + p2 + p3 + p4 + p5 + p6 + p7 + p8 + plot_layout(nrow = 2)
```

## Missing value

```{r, include = FALSE}
r1 <- 
  raster(res = c(1, 1),
         xmn = 1, xmx = 4, ymn = 1, ymx = 4,
         vals = 1)
values(r1)[3] <- NA
writeRaster(r1, "r1.tif", overwrite = TRUE)
r2 <- 
  raster(res = c(1, 1),
         xmn = 2, xmx = 5, ymn = 2, ymx = 5,
         vals = 2)
values(r2)[7] <- NA
writeRaster(r2, "r2.tif", overwrite = TRUE)

r3 <- merge(r1, r2)
r4 <- merge(r2, r1)
r5 <- mosaic(r1, r2, fun = "mean")
r6 <- mosaic(r2, r1, fun = "mean")
dummy <- mosaic_rasters(c("r1.tif", "r2.tif"), dst_dataset = "r7.tif", fun = "mean")
r7 <- raster("r7.tif")
dummy <- mosaic_rasters(c("r2.tif", "r1.tif"), dst_dataset = "r8.tif")
r8 <- raster("r8.tif")
```

```{r}
p1 <- my_plot(r1, "r1", colour = "red")
p2 <- my_plot(r2, "r2", colour = "red")
p3 <- 
  my_plot(r3, "r1, r2") +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 5.5, label = 'merge(r1, r2)', hjust = 0)
p4 <- 
  my_plot(r4, "r2, r1") +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 5.5, label = 'merge(r2, r1)', hjust = 0)
p5 <- 
  my_plot(r5, "r1, r2") +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 5.5, label = 'mosaic(r1, r2, fun = "mean")', hjust = 0)
p6 <- 
  my_plot(r6, "r2, r1") +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 5.5, label = 'mosaic(r2, r1, fun = "mean")', hjust = 0)
p7 <- 
  my_plot(r7, "r1, r2") +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 5.5, label = 'mosaic_rasters(r1, r2)', hjust = 0)
p8 <- 
  my_plot(r8, "r2, r1") +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 5.5, label = 'mosaic_rasters(r2, r1)', hjust = 0)
p1 + p2 + p3 + p4 + p5 + p6 + p7 + p8 + plot_layout(nrow = 2)
```

# Tile misalignment 

## Base

```{r, include = FALSE}
r1 <- 
  raster(res = c(1, 1),
         xmn = 1, xmx = 4, ymn = 1, ymx = 4,
         vals = 1)
writeRaster(r1, "r1.tif", overwrite = TRUE)
r2 <- 
  raster(res = c(1, 1),
         xmn = 1.5, xmx = 4.5, ymn = 1.5, ymx = 4.5,
         vals = 2)
writeRaster(r2, "r2.tif", overwrite = TRUE)

#r3 <- merge(r1, r2)
#r4 <- merge(r2, r1)
#r5 <- mosaic(r1, r2, fun = "mean")
#r6 <- mosaic(r2, r1, fun = "mean")
dummy <- mosaic_rasters(c("r1.tif", "r2.tif"), dst_dataset = "r7.tif", fun = "mean")
r7 <- raster("r7.tif")
dummy <- mosaic_rasters(c("r2.tif", "r1.tif"), dst_dataset = "r8.tif")
r8 <- raster("r8.tif")
```


```{r, fig.height = 3}
p1 <- my_plot(r1, "r1", colour = "red")
p2 <- my_plot(r2, "r2", colour = "red")
p7 <- 
  my_plot(r7, "r1, r2") +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 5.5, label = 'mosaic_rasters(r1, r2)', hjust = 0)
p8 <- 
  my_plot(r8, "r2, r1") +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 5.5, label = 'mosaic_rasters(r2, r1)', hjust = 0)
p1 + p2 + p7 + p8 + plot_layout(nrow = 1)
```

## Missing value

```{r, include = FALSE}
r1 <- 
  raster(res = c(1, 1),
         xmn = 1, xmx = 4, ymn = 1, ymx = 4,
         vals = 1)
values(r1)[3] <- NA
writeRaster(r1, "r1.tif", overwrite = TRUE)
r2 <- 
  raster(res = c(1, 1),
         xmn = 1.5, xmx = 4.5, ymn = 1.5, ymx = 4.5,
         vals = 2)
values(r2)[7] <- NA
writeRaster(r2, "r2.tif", overwrite = TRUE)

#r3 <- merge(r1, r2)
#r4 <- merge(r2, r1)
#r5 <- mosaic(r1, r2, fun = "mean")
#r6 <- mosaic(r2, r1, fun = "mean")
dummy <- mosaic_rasters(c("r1.tif", "r2.tif"), dst_dataset = "r7.tif", fun = "mean")
r7 <- raster("r7.tif")
dummy <- mosaic_rasters(c("r2.tif", "r1.tif"), dst_dataset = "r8.tif")
r8 <- raster("r8.tif")
```

```{r, fig.height = 3}
p1 <- my_plot(r1, "r1", colour = "red")
p2 <- my_plot(r2, "r2", colour = "red")
p7 <- 
  my_plot(r7, "r1, r2") +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 5.5, label = 'mosaic_rasters(r1, r2)', hjust = 0)
p8 <- 
  my_plot(r8, "r2, r1") +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 5.5, label = 'mosaic_rasters(r2, r1)', hjust = 0)
p1 + p2 + p7 + p8 + plot_layout(nrow = 1)
```


# Different resolutions

```{r}
my_plot <- function(r, object = "r1", colour, at) {
  
  if(missing(at)) {
    at <- tidy_raster(r) %>% mutate(object = object)
  }
  p <- 
    r %>% 
    r2df(object) %>% 
    ggplot() +
    geom_tile(aes(x, y, fill = z), colour = "white") +
    geom_text(aes(x, y, label = z), colour = "white") +
    facet_wrap(~ object, nrow = 1) +
    coord_equal() +
    theme(legend.position = "none",
          panel.grid.minor = element_blank())
  
  if(!missing(colour)) {
    p <-
      p +
      geom_rect(data = at, aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = colour)
  }
  
  return(p)
}
```


## Base

```{r, include = FALSE}
r1 <- 
  raster(res = c(2, 2),
         xmn = 0, xmx = 4, ymn = 0, ymx = 4,
         vals = 1)
writeRaster(r1, "r1.tif", overwrite = TRUE)
r2 <- 
  raster(res = c(3, 3),
         xmn = 1, xmx = 7, ymn = 1, ymx = 7,
         vals = 2)
writeRaster(r2, "r2.tif", overwrite = TRUE)

#r3 <- merge(r1, r2)
#r4 <- merge(r2, r1)
#r5 <- mosaic(r1, r2, fun = "mean")
#r6 <- mosaic(r2, r1, fun = "mean")
dummy <- mosaic_rasters(c("r1.tif", "r2.tif"), dst_dataset = "r7.tif", fun = "mean")
r7 <- raster("r7.tif")
dummy <- mosaic_rasters(c("r2.tif", "r1.tif"), dst_dataset = "r8.tif")
r8 <- raster("r8.tif")
```

```{r, fig.height=3}
p1 <- 
  my_plot(r1, "r1", colour = "red") +
  scale_x_continuous(name = NULL, breaks = 0:9, limits = c(0, 9)) +
  scale_y_continuous(name = NULL, breaks = 0:9, limits = c(0, 9))
p2 <- 
  my_plot(r2, "r2", colour = "red") +
  scale_x_continuous(name = NULL, breaks = 0:9, limits = c(0, 9)) +
  scale_y_continuous(name = NULL, breaks = 0:9, limits = c(0, 9))

p7 <- 
  my_plot(r7, "r1, r2") +
  scale_x_continuous(name = NULL, breaks = 0:9, limits = c(0, 9)) +
  scale_y_continuous(name = NULL, breaks = 0:9, limits = c(0, 9)) +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 8.5, label = 'mosaic_rasters(r1, r2)', hjust = 0)
p8 <- 
  my_plot(r8, "r2, r1") +
  scale_x_continuous(name = NULL, breaks = 0:9, limits = c(0, 9)) +
  scale_y_continuous(name = NULL, breaks = 0:9, limits = c(0, 9)) +
  geom_rect(data = r1 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  geom_rect(data = r2 %>% tidy_raster(), aes(xmin = xmin, xmax = xmax, ymin = ymin, ymax = ymax), alpha = 0, colour = "red") +
  annotate("text", x = 0.5, y = 8.5, label = 'mosaic_rasters(r2, r1)', hjust = 0)
p1 + p2 + p7 + p8 + plot_layout(nrow = 1)
```



```{r, eval = FALSE}

## Missing value

# Tidy raster system

# Base 1, then 2, 4, 8, 16, 32, 64, 128, 256, ...
r1 <- 
  raster(res = c(1, 1),
         xmn = 0, xmx = 256, ymn = 0, ymx = 256,
         vals = 1:(256*256))
plot(r1)
aggregate(r1, fact = 2)
aggregate(r1, fact = 4)
aggregate(r1, fact = 8)
aggregate(r1, fact = 128) %>% plot()

```



```{r, eval = FALSE}
r <- raster("data/rayshaded/rayshaded_jokulbanki_a2015_30m.tif")
isn2004 <- proj4string(r)
r20 <- 
  raster(res = c(20, 20),
         xmn = 1220000, xmx = 1220100,
         ymn = 120000, ymx = 120100,
         crs = isn2004,
         vals = rep(1:5, 5))
r30 <- 
  raster(res = c(30, 30),
         xmn = 1220000, xmx = 1220150,
         ymn = 120000, ymx = 120150,
         crs = isn2004,
         vals = rep(1:5, 5))
plot(r30)
plot(r20, add = TRUE)
```
