---
title: "More ggplot2"
subtitle: "Part 2"
output:
  html_document:
    fig_height: 4
    fig_width: 9
    highlight: haddock
    theme: united
    toc: yes
    toc_float: yes
    toc_depth: 2
---

```{r, echo = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
```

```{r, echo = FALSE}
#theme_set(theme_grey(base_size = 16))
cl = function(x, color = "blue"){
  outputFormat = knitr::opts_knit$get("rmarkdown.pandoc.to")
  if(outputFormat == 'latex')
    paste("\\textcolor{",color,"}{", x ,"}",sep="")
  else if(outputFormat == 'html')
    paste("<font color='",color,"'>", x ,"</font>",sep="")
  else
    x
}
```

```{r}
minke <- read.csv("ftp://ftp.hafro.is/pub/data/csv/minke.csv",
                  stringsAsFactors = FALSE)
```

## Preamble

Unlike base-plot ggplot2 comes with a lot of defaults, such as axis scales and labels, default colours etc. In this presentation we deal with  ...



## Formatting axis values

```{r}
# https://stackoverflow.com/questions/33302424/format-latitude-and-longitude-axis-labels-in-ggplot
scale_longitude <- function(min = -180, max = 180, step = 1, ...) {
  breaks <- seq(min, max, step)
  labels <- 
    ifelse(breaks < 0,
           paste0(breaks, "\u00B0", "W"),
           paste0(breaks, "\u00B0", "E"))
  return(scale_x_continuous(name = NULL, breaks = breaks, labels = labels, ...))
}
scale_latitude <- function(min = -90, max = 90, step = 0.5, ...) {
  breaks <- seq(min, max, step)
  labels <- 
    ifelse(breaks < 0,
           paste0(breaks, "\u00B0", "S"),
           paste0(breaks, "\u00B0", "N"))
  return(scale_y_continuous(name = NULL, breaks = breaks, labels = labels, ...))
}

p <- 
  ggplot(geo::island, aes(lon, lat)) +
  coord_quickmap()
p +
  geom_path() +
  scale_longitude(step = 2) +
  scale_latitude(step = 1)


p +
  geom_path() +
  scale_x_continuous(breaks = seq(-25, -10, by = 1),
                     labels = paste(seq(-25, -10, by = 1), "W")) +
  scale_y_continuous(breaks = seq(63, 67, by = 0.5),
                     labels = paste(seq(63, 67, by = 0.5), "N")) 
  
```

## ICES rectangles


```{r}
scale_longitude_ices <- function(min = -44, max = 68.5, step = 1, ...) {
  breaks <- seq(min + 0.5, max - 0.5, step)
  labels <- geo::d2ir(60, breaks) %>% str_sub(3)
  return(scale_x_continuous(name = NULL, breaks = breaks, labels = labels, ...))
}
scale_latitude_ices <- function(min = 36, max = 84.5, step = 0.5, ...) {
  breaks <- seq(min + 0.25, max - 0.25, step)
  labels <- geo::d2ir(breaks, 0) %>% str_sub(1, 2)
  return(scale_y_continuous(name = NULL, breaks = breaks, labels = labels, ...))
}

p +
  geom_path() +
  scale_longitude_ices() +
  scale_latitude_ices()
  
```

```{r}
ir <- 
  sf::read_sf("ftp://ftp.hafro.is/pub/data/shapes/ices_rectangles.gpkg") %>% 
  filter(between(west, -25, -14),
         between(south, 63, 66))
ggplot() +
  #geom_sf(data = ir) +
  geom_path(data = geo::island, aes(lon, lat),
            colour = "grey") +
  geom_text(data = ir,
            aes(x = west + 0.5, y = south + 0.25,
                label = icesname),
            angle = 45, 
            colour = "red",
            size = 3) +
  scale_longitude_ices() +
  scale_latitude_ices() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_line(size = 1),
        axis.ticks = element_blank()) +
  coord_quickmap()
```

## Colour scales


## Scalebars and north arrow

```{r}
library(ggspatial)
m <- 
  ggplot() +
  geom_polygon(data = geo::island, aes(lon, lat), fill = "grey") +
  scale_x_continuous(NULL, NULL) +
  scale_y_continuous(NULL, NULL) +
  coord_quickmap()
m +
  annotation_scale(location = "bl", width_hint = 0.5) +
  annotation_north_arrow(location = "bl", which_north = "true", 
        pad_x = unit(0.75, "in"), pad_y = unit(0.5, "in"),
        style = north_arrow_fancy_orienteering)
```

## datras doodle

```{r}
smb <- 
  read.csv("ftp://ftp.hafro.is/pub/data/csv/is_smb.csv",
           stringsAsFactors = FALSE) %>% 
  as_tibble()

library(GGally)
by.rect <- 
  smb %>% 
  #filter(ir_lon <= -22, ir_lat >= 66) %>% 
  rename(n = cod_n) %>% 
  mutate(n = ifelse(n > quantile(n, 0.99), quantile(n, 0.99), n)) %>% 
  group_by(year, ir_lon, ir_lat) %>% 
  summarise(n = mean(n))
n.glyph <-
  by.rect %>% 
  #mutate(n = ifelse(n > 0 & n > quantile(n, 0.40), quantile(n, 0.40), n)) %>% 
  glyphs(x_major = "ir_lon", 
         y_major = "ir_lat",
         x_minor = "year", 
         y_minor = "n", 
         width = 1, 
         height = 0.5)


tows <- 
  smb %>% 
  filter(year == 2019)

n.glyph %>% 
  mutate(pos = ifelse(n != 0, TRUE, FALSE),
         base = ir_lat - 0.25,
         gy = ifelse(n == 0, gy + 0.005, gy)) %>% 
  ggplot() +
  theme_bw() +
  geom_linerange(aes(x = gx, ymin = base, ymax = gy),
                 colour = "black") +
  geom_segment(data = tows,
                aes(x = lon1, y = lat1, xend = lon2, yend = lat2),
                colour = "red") +
  geom_path(data = geo::island, aes(lon, lat)) +
  coord_quickmap() +
  scale_longitude_ices() +
  scale_latitude_ices() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_line(size = 1),
        axis.ticks = element_blank())
```

Standardize within rectangle (value between 0 and 1):

```{r, eval = FALSE}
by.rect.relative <- 
  by.rect %>% 
  group_by(ir_lon, ir_lat) %>% 
  mutate(n = scale::rescale(n, to = c(0, 1)))


n.glyph <-
  by.rect.relative %>% 
  #mutate(n = ifelse(n > 0 & n > quantile(n, 0.40), quantile(n, 0.40), n)) %>% 
  glyphs(x_major = "ir_lon", 
         y_major = "ir_lat",
         x_minor = "year", 
         y_minor = "n", 
         width = 1, 
         height = 0.5)


tows <- 
  smb %>% 
  filter(year == 2019)

n.glyph %>% 
  mutate(pos = ifelse(n != 0, TRUE, FALSE),
         base = ir_lat - 0.25,
         gy = ifelse(n == 0, gy + 0.005, gy)) %>% 
  ggplot() +
  theme_bw() +
  geom_linerange(aes(x = gx, ymin = base, ymax = gy),
                 colour = "black") +
  geom_segment(data = tows,
                aes(x = lon1, y = lat1, xend = lon2, yend = lat2),
                colour = "red") +
  geom_path(data = geo::island, aes(lon, lat)) +
  coord_quickmap() +
  scale_longitude_ices() +
  scale_latitude_ices() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_line(size = 1),
        axis.ticks = element_blank())
```


## Arranging plot

### Patchwork

```{r}
library(patchwork)

```


### Cowplot for inserts



